#!/usr/bin/env bash

set -e

dirs=(/etc/khan /etc/ssl/khan /var/cache/khan /var/log/khan)

# Create the khan user and group.
adduser --home ${dirs[0]} --system --group --no-create-home --quiet khan || true

# Ensure expected dirs are created,
# and ensure dpkg removes them on uninstall.
mkdir -p ${dirs[@]}

# Ensure all directories are owned by the created user.
chown -R khan:khan ${dirs[@]}
